version: "3"
services:
  cassandra:
    image: cassandra:latest
    volumes:
      - /home/yannic/cassandra_data/:/var/lib/cassandra
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
      - "9142:9142"
    container_name: "pr-local"